### PR TITLE
[FIX] fix filenaming

### LINKED ISSUE #38: facerep test failures
CI failure with matlab 2020a

```matlab
  {Error using run_spmup_bids (line 246)
  No such file or directory
  
  Error in facerep (line 77)
  [subjects, opt]    = run_spmup_bids(BIDS, subjects, options);
  
  Error in run (line 91)
  evalin('caller', strcat(script, ';'));
  
  Error in system_tests_facerep (line 12)
  run facerep;
  
  Error in run (line 91)
  evalin('caller', strcat(script, ';'));
  
  Error in command_b9667c74_ab8e_4895_ae85_5ec3eaca51ee (line 2)
  run system_tests_facerep;
  } 
```

Getting a different error locally with matlab 2018a

```matlab
------------------
spm_hrf_boost done
------------------------------
 running spmup_timeseries on /home/remi/github/bidspm/lib/spmup/system_test/facerep/raw/derivatives/sub-01/func/spmup_stats/Res_0001.nii
------------------------------
Checking Yeo's networks to organize GM voxels
---------------------------------------
session  finished!
---------------------------------------
Error using table (line 307)
'tSNR GM run 1' is not a valid variable name.

Error in spmup_BIDS_QCtables (line 80)
                    fMRIQA = table( cellfun(@(x) x.func_qa{session}{run}.preproc_tSNR.GM, subjects)',...

Error in run_spmup_bids (line 228)
    table_name  = spmup_BIDS_QCtables(subjects, 'fMRI');

Error in facerep (line 77)
[subjects, opt]    = run_spmup_bids(BIDS, subjects, options);
```

I suspect that I cannot have spaces in this there:

https://github.com/CPernet/spmup/blob/3aab2a07c0b3ece8b40da263a01db9303185c0ef/bids/spmup_BIDS_QCtables.m#L84

Will try fixing that.

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #38

### CODE REVIEW

**Review by CPernet — COMMENTED** [review]
In general i agree with no space but then, because the table is send to make a the figure, this needs change because underscore messes up titles

**Review by CPernet — APPROVED** [review]

**Review by CPernet — APPROVED** [review]

**Review by CPernet — APPROVED** [review]

**Review by CPernet — CHANGES_REQUESTED** [review]
since this is renamed later I don't think we should print that

**Review by CPernet — APPROVED** [review]

**Comment by CPernet** [comment]
will likely remove the print from tables + needs title fix for figures because of table variable underscore

**Comment by Remi-Gau** [comment]
> since this is renamed later I don't think we should print that

Fair enough this was more for print debugging anyway.

**Pull request merged**
